# -*- coding: utf-8 -*-
"""Лаб№1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1obG_W1gvlxbvFNdKEk9evh8UgNMFr9PU

Лабораторная работа №1
"""

a = 5
b = 2
print(a + b)

"""Площадь равнобедренного треугольника"""

a = 7.5
b = 7.5
c = 6
h = (b**2 - (c/2)**2)**0.5
S = 0.5 * a * h
print(S)

a = 7.5
print(a**2)

print("Hello World")

"""Вычислить"""

a = 2
b = 3
c = 5
print((a**2 + b**2 - c**3) / 2)

"""Самостоятельные задания

задание№1
"""

a = 5
b = int(input())
c = a * b
print(c)

"""задание№2"""

a = int(input())
b = int(input())
v = a + b
c = v**2
print(c)

"""задание№3"""

a = 15
b = 10
c = int(input())
v = a + b
n = v / c
print(n)

"""задание№4"""

a = int(input())
b = int(input())
c = a + b
n = c**2
print(n)



"""задание№5"""

a = 6
b = 7
c = 4
P = (a + b + c)/2
print(P*2) 
S = (P * (P - a) * (P - b) * (P - c))**0.5
print(S)

"""задание№6"""

a = 5
b = 7
c = ((a**3 + 14) / 5) * b
print(c)

"""задание№7"""

a = 5
n = 3
c = a**2 / n
print(a**2 // n)

"""задание№8"""

a = float(input())
b = float(input())
c = a // b
print(c)

a = int(input())
b = int(input())
c = a * b
print(c)

a = int(input())
b = int(input())
c = a % b
print(c)

"""Задача повышенной сложности

№1
"""

n = 789456123
print(n / 60 / 60 // 24)
print(n / 60 // 60)
print(n // 60)

"""№2"""

n = int(input())
S1 = str(n)
S2 = S1 * 2
S3 = S1 * 3
print(int(S1) + int(S2) + int(S3))