# -*- coding: utf-8 -*-
"""Лаб 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15-yKjQMcF-XZS_Z8CiOzFQjx9GaV-Il4
"""



a = int(input())
if a == 1:
  print('Январь')
elif a == 2:
  print('Февраль')
elif a == 3:
  print('Март')
elif a == 4:
  print('Апрель')
elif a == 5:
  print('Май')
elif a == 6:
  print('Июнь')
elif a == 7:
  print('Июль')
elif a == 8:
  print('Август')
elif a == 9:
  print('Сентябрь')
elif a == 10:
  print('Октябрь')
elif a == 11:
  print('Ноябрь')
elif a == 12:
  print('Декабрь')



a = int(input())
if a % 2 == 1:
  print("нечетное")
elif a%2 !=1:
  print("четное")



N = int(input())
if N > 40:
  print("stonks c:")
elif N < 40:
  print("not stonks :c")



def is_year_leap():
  year = int(input("Введите год"))
  if (year % 4 == 0 and (year % 100 != 0) or (year % 400 == 0)):
    return True
  else:
    return False
is_year_leap()

def is_prime():
  n = int(input())
  for i in range(2, n):
    if n % i == 0:
      return False
    else:
      return True
is_prime()

a = float(input("Введите переменную a"))
b = float(input("Введите переменную b"))
c = a/b
if c == 3.6:
  a,b = b,a
  print("a равно = ", a)
  print("b равно = ", b)
else:
  if (138/2)**1.3 <= b <= abs((-69/28**5.1)):
      a,b = b,a
      print("a равно = ", a)
      print("b равно = ", b)

a = int(input())
b = int(input())
c = int(input())
d = int(input())
e = int(input())
cnt = 0
cnt1 = 0
if a!=b!=c!=d!=e:
  print(True)
if a % 2 == 0:
  cnt += 1
if b % 2 == 0:
  cnt += 1
if c % 2 == 0:
  cnt += 1
if d % 2 == 0:
  cnt += 1
if e % 2 == 0:
  cnt += 1
print(cnt)
if a < 0:
  cnt1 += 1
if b < 0:
  cnt1 += 1
if c < 0:
  cnt1 += 1
if d < 0:
  cnt1 += 1
if e < 0:
  cnt1 += 1
print(cnt1)

